elasticsearch:
    image: elasticsearch:latest
    volumes:
            - /srv/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
            - "9200:9200"

logstash:
    image: logstash:latest
    environment:
            TZ: Europe/Paris
    expose:
            - "12201"
    ports:
            - "12201:12201"
            - "12201:12201/udp"
    volumes:
            - ./conf:/conf
    links:
            - elasticsearch:elasticsearch
    command: logstash -f /conf/beats.conf --verbose

kibana:
    image: kibana:latest
    links:
            - elasticsearch:elasticsearch
    ports:
            - "5601:5601"

filebeat: 
    image: prima/filebeat
    volumes:
        - ./conf/filebeat.yml:/filebeat.yml
        - /var/log/apache2:/logs/apache2
        - /home/fabien/home/workspace/ffopen/log:/logs/ffopen
    links: 
        - logstash:logstash
    
